#!/bin/bash
FORCE=0
test "$1" == '-f' && FORCE=1

DOTFILES=$(cd "$(dirname "$0")" && pwd)
CONFIG_DIR=${XDG_CONFIG_HOME:=$HOME/.config}

function install_to_config () {
  dotfile="${DOTFILES}/${1}"
  target="${CONFIG_DIR}/${2}"

  if [[ ! -e $target || $FORCE -eq 1 ]]; then
    ln -sfnv $dotfile $target
  else
    echo "$target already exists, ignoring..."
  fi
}

mkdir -p "${XDG_CONFIG_HOME}/nvim"

install_to_config nvim/init.vim nvim/init.vim
