#!/usr/bin/env zsh
FORCE=0
test "$1" = '-f' && FORCE=1

DOTFILES=$(cd "$(dirname "$0")" && pwd)

function link_to_home () {
  dotfile="${DOTFILES}/${1}"
  target="${HOME}/${2}"

  if [[ ! -e $target || $FORCE -eq 1 ]]; then
    ln -sfnv $dotfile $target
  else
    echo "$target already exists, skipping..." 1>&2
  fi
}

# Install dotfiles
link_to_home zsh/.zshrc .zshrc
link_to_home zsh/aliases.zsh aliases.zsh

read 'choice?Install sparx-specific config? [y/N] '
[[ $choice =~ ^[Yy] ]] && link_to_home zsh/.zshrc.sparx .zshrc.sparx
