#!/usr/bin/env zsh
FORCE=0
[[ "$1" = '-f' ]] && FORCE=1
DOTFILES=$(cd "$(dirname "$0")" && pwd)
source "$DOTFILES/helpers.zsh"

if [[ ! -e "$CONFIG_DIR/nvim" || $FORCE -eq 1 ]]; then
  ln -sfnv "$DOTFILES/nvim-lua" "$CONFIG_DIR/nvim"
fi

# Set up packer.nvim
PACKER_DIR="$HOME/.local/share/nvim/site/pack/packer/start/packer.nvim"
if [[ $FORCE -eq 1 ]]; then
  echo "Removing existing packer..."
  rm -rf "$PACKER_DIR"
fi
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim
