#!/bin/bash
FORCE=0
test "$1" == '-f' && FORCE=1

DOTFILES=$(cd "$(dirname "$0")" && pwd)
CONFIG_DIR=${XDG_CONFIG_HOME:=$HOME/.config}
NVIM_DIR="$CONFIG_DIR/nvim"

function link_file () {
  dotfile="${1}"
  target="${2}"

  if [[ ! -e $target || $FORCE -eq 1 ]]; then
    ln -sfnv "$dotfile" "$target"
  else
    echo "$target already exists, skipping..."
  fi
}

# Link main config file
mkdir -p "$NVIM_DIR"
link_file "$DOTFILES/nvim/init.lua" "$NVIM_DIR/init.lua"

# Link file-specific settings
link_file "$DOTFILES/nvim/ftplugin" "$NVIM_DIR/ftplugin"

# Install packer
PACKER_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/nvim/site/pack/packer/start/packer.nvim"
if [[ ! -e $PACKER_DIR || $FORCE -eq 1 ]]; then
  echo "Installing packer..."
  git clone https://github.com/wbthomason/packer.nvim "$PACKER_DIR"
else
  echo "packer already installed, skipping..."
fi
