#!/usr/bin/env zsh
FORCE=0
[[ "$1" = '-f' ]] && FORCE=1
DOTFILES=$(cd "$(dirname "$0")" && pwd)
source "$DOTFILES/helpers.zsh"

FZF_DIR="$HOME/.fzf"
pull_repo https://github.com/junegunn/fzf.git "$FZF_DIR"
$FZF_DIR/install --bin
