#!/bin/bash
FORCE=0
test "$1" == '-f' && FORCE=1

FZF_DIR="$HOME/.fzf"

if [[ $FORCE == 1 && -e "$FZF_DIR" ]]; then
  echo "$FZF_DIR found, removing..."
  rm -rf "$FZF_DIR"
fi

if [[ ! -e "$FZF_DIR" ]]; then
  echo "$FZF_DIR not found, installing..."
  git clone --depth 1 https://github.com/junegunn/fzf.git "$FZF_DIR"
elif [[ -d "$FZF_DIR" ]]; then
  echo "$FZF_DIR found, updating..."
  (cd "$FZF_DIR" && git pull)
fi

$FZF_DIR/install --all
