#!/usr/bin/env zsh
FORCE=0
[[ "$1" = '-f' ]] && FORCE=1
DOTFILES=$(cd "$(dirname "$0")" && pwd)
source "$DOTFILES/helpers.zsh"

# Install dotfiles
link_to_home zsh/.zshrc .zshrc
link_to_home zsh/.zsh_aliases .zsh_aliases

# Install zplug plugin manager
pull_repo https://github.com/zplug/zplug "$HOME/.zplug"

# Install optional dotfiles
read 'choice?Install sparx config? [y/N] '
[[ $choice =~ ^[Yy] ]] && link_to_home zsh/.zshrc.sparx .zshrc.sparx
