#!/usr/bin/env zsh
FORCE=0
[[ "$1" = '-f' ]] && FORCE=1
DOTFILES=$(cd "$(dirname "$0")" && pwd)
source "$DOTFILES/helpers.zsh"

mkdir -p "$CONFIG_DIR/kitty"

link_to_config kitty/kitty.conf kitty/kitty.conf

read 'choice?Install sparx kitty config? [y/N] '
[[ $choice =~ ^[Yy] ]] && link_to_config kitty/sparx.conf kitty/sparx.conf
