#!/usr/bin/env bash
DOTFILES=$(dirname $(readlink -f $0))
ZSH_PLUGINS="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins"

function install_to_home () {
  dotfile="${DOTFILES}/${1}"
  target="${HOME}/${2}"

  if [ ! -e $target -a ! -L $target ]; then
    ln -sv $dotfile $target
  else
    echo "$target already exists, skipping..." 1>&2
  fi
}

# Install oh-my-zsh if not already installed
if [ ! -e "${HOME}/.oh-my-zsh" ]; then
  RUNZSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  rm "${HOME}/.zshrc"
else
  echo ".oh-my-zsh already exists, skipping..." 1>&2
fi

# Install dotfiles
install_to_home zsh/.zshrc .zshrc

# Add oh-my-zsh plugins
if [ ! -e "${ZSH_PLUGINS}/zsh-syntax-highlighting" ]; then
  git clone https://github.com/zsh-users/zsh-syntax-highlighting "${ZSH_PLUGINS}/zsh-syntax-highlighting"
else
  echo "${ZSH_PLUGINS}/zsh-syntax-highlighting already exists, skipping..." 1>&2
fi

if [ ! -e "${ZSH_PLUGINS}/zsh-z" ]; then
  git clone https://github.com/agkozak/zsh-z "${ZSH_PLUGINS}/zsh-z"
else
  echo "${ZSH_PLUGINS}/zsh-z already exists, skipping..." 1>&2
fi

