local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, { desc = '[f]ind [f]iles' })
vim.keymap.set('n', '<leader>fg', builtin.git_files, { desc = '[f]ind [g]it files' })
vim.keymap.set('n', '<leader>fs', builtin.live_grep, { desc = '[f]ind [s]tring (grep)' })
vim.keymap.set('n', '<leader>fo', builtin.oldfiles, { desc = '[f]ind recently [o]pened files' })
vim.keymap.set('n', '<leader>fh', builtin.help_tags, { desc = '[f]ind [h]elp' })
vim.keymap.set('n', '<leader>fw', builtin.grep_string, { desc = '[f]ind current [w]ord' })
vim.keymap.set('n', '<leader>f:', builtin.commands, { desc = '[f]ind [:]command' })
vim.keymap.set('n', '<leader><space>', builtin.buffers, { desc = '[ ] find existing buffers' })

--vim.keymap.set('n', '<leader>ss', function()
--  builtin.grep_string({ search = vim.fn.input("Grep > ") })
--end, { desc = '[S]earch for [S]trings (Grep)' })
--vim.keymap.set('n', '<leader>fg', builtin.live_grep, {})
--vim.keymap.set('n', '<leader>fb', builtin.buffers, {})
--vim.keymap.set('n', '<leader>fh', builtin.help_tags, {})
