#!/usr/bin/env zsh
FORCE=0
[[ "$1" = '-f' ]] && FORCE=1
DOTFILES=$(cd "$(dirname "$0")" && pwd)
source "$DOTFILES/helpers.zsh"

mkdir -p "$CONFIG_DIR/nvim"

# Link main config file
link_to_config nvim-old/init.vim nvim/init.vim

# Link filetype-specific settings (dir)
link_to_config nvim-old/ftplugin nvim/ftplugin

# Install vim-plug
if [[ ! -e "$CONFIG_DIR/nvim/autoload/plug.vim" || $FORCE -eq 1 ]]; then
  echo "Installing vim-plug..."
  curl -sfLo ~/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
else
  echo "vim-plug already installed, skipping..."
fi
